unbind C-b
set -g prefix C-a

set -g default-terminal xterm-256color
set -ga terminal-overrides ",xterm-256color*:Tc"

set -g history-limit 20000
set -g renumber-windows on

set -sg escape-time 0

set -g base-index 1
set -g pane-base-index 1

unbind c
bind c new-window -c '#{pane_current_path}'

bind | split-window -h -c '#{pane_current_path}'
bind \\ split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

setw -g mode-keys vi
set-window-option -g mode-keys vi

set -g mouse off

tm_color_active=cyan
tm_color_inactive=colour241
tm_color_feature=white

set-option -g status-style fg=$tm_color_active,bg=default

set-window-option -g window-status-style fg=$tm_color_inactive,bg=default
set -g window-status-format "#I #W"

set-window-option -g window-status-current-style fg=$tm_color_active,bg=default
set-window-option -g window-status-current-format "#[bold]#I #W"

set-option -g pane-border-style fg=$tm_color_inactive
set-option -g pane-active-border-style fg=$tm_color_active

set-option -g message-style fg=$tm_color_active

set -g status-left "#[fg=$tm_color_feature,bold] #S  "
set -g status-right " #[fg=$tm_color_inactive] %R"

set -g status-interval 60
